type Query {
  getUserInfo(handle: String!): User!
}

5type Tweet {
  tweet_id: String!
  tweet: String!
  handle: String!
  created_at: String!
}

12type TweetConnection {
  items: [Tweet!]!
  nextToken: String
}

17type User {
  name: String!
  description: String!
  followers_count: Int!
  following: [String!]!
  topTweet: Tweet
  tweets(limit: Int!, nextToken: String): TweetConnection
}